# Conda environment, that includes all packages that are necessary for
# the complete Biotite development process.

name: biotraj-dev

channels:
  - anaconda
  - conda-forge
  - salilab
  - bioconda

dependencies:
  - python =3.10
  # Package building
  - cython >=3.0
  - pip >=10.0
  - pyparsing >=3.1.2
  - setuptools >=30.0
  - wheel >=0.30
  # Biotite dependencies
  - msgpack-python >=0.5.6
  - networkx >=2.0
  - numpy >=2.0
  - requests >=2.12

  # Testing
  - pytest >=7.0
